GET_LATEST_PICTURES = "GET_LATEST_PICTURES_N"
SEND_LATEST_PICTURES = "SEND_LATEST_PICTURES"
PICTURE_TAKEN = "PICTURE_TAKEN"




# from mqtt_topics import GET_LATEST_PICTURES, SEND_LATEST_PICTURES

# client.subscribe(GET_LATEST_PICTURES)
# client.publish(SEND_LATEST_PICTURES, payload)